from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional, List
from app.services.ai_service import generate_roadmap, generate_quick_tips
from app.database import SessionLocal
from app.models.roadmap import Roadmap
from app.models.user import User
from app.models.resume import Resume

router = APIRouter(prefix="/roadmap", tags=["roadmap"])

class RoadmapRequest(BaseModel):
    clerk_user_id: str
    target_company: Optional[str] = "a top tech company"
    target_role: Optional[str] = "Software Engineer"
    weeks_available: Optional[int] = 8
    missing_skills: Optional[List[str]] = []
    current_skills: Optional[List[str]] = []

@router.get("/test")
def test_roadmap_route():
    return {"message": "Roadmap route working"}

@router.post("/generate")
def generate_student_roadmap(request: RoadmapRequest):
    """Generate a personalised AI roadmap for a student."""

    if request.weeks_available < 1 or request.weeks_available > 20:
        raise HTTPException(
            status_code=400,
            detail="Weeks available must be between 1 and 20"
        )

    db = SessionLocal()
    try:
        # Get user profile
        user = db.query(User).filter(User.id == request.clerk_user_id).first()

        student_name = "Student"
        branch = "CSE"
        graduation_year = "2026"
        cgpa = "7.5"
        current_skills = request.current_skills
        missing_skills = request.missing_skills

        if user:
            student_name = user.full_name or "Student"
            branch = user.branch or "CSE"
            graduation_year = user.graduation_year or "2026"
            cgpa = user.cgpa or "7.5"

        # If no skills provided, try to get from latest resume
        if not current_skills and not missing_skills:
            resume = db.query(Resume).filter(
                Resume.user_id == request.clerk_user_id,
                Resume.is_active == True
            ).first()
            if resume and resume.missing_keywords:
                missing_skills = resume.missing_keywords[:10]

        print(f"Generating roadmap for {student_name} targeting {request.target_company}")

        # Call Groq AI
        roadmap_content = generate_roadmap(
            student_name=student_name,
            branch=branch,
            graduation_year=graduation_year,
            cgpa=cgpa,
            current_skills=current_skills,
            missing_skills=missing_skills,
            target_company=request.target_company,
            target_role=request.target_role,
            weeks_available=request.weeks_available,
        )

        # Save to database
        new_roadmap = Roadmap(
            user_id=request.clerk_user_id,
            target_company=request.target_company,
            target_role=request.target_role,
            weeks_available=request.weeks_available,
            current_skills=", ".join(current_skills),
            missing_skills=", ".join(missing_skills),
            roadmap_content=roadmap_content,
            is_active=True,
        )
        db.add(new_roadmap)
        db.commit()

        return {
            "success": True,
            "roadmap": roadmap_content,
            "roadmap_id": str(new_roadmap.id),
            "target_company": request.target_company,
            "target_role": request.target_role,
            "weeks": request.weeks_available,
        }

    except Exception as e:
        db.rollback()
        print(f"Roadmap generation error: {str(e)}")
        raise HTTPException(
            status_code=500,
            detail=f"Failed to generate roadmap: {str(e)}"
        )
    finally:
        db.close()

@router.get("/history/{clerk_user_id}")
def get_roadmap_history(clerk_user_id: str):
    """Get all roadmaps generated by a user."""
    db = SessionLocal()
    try:
        roadmaps = db.query(Roadmap).filter(
            Roadmap.user_id == clerk_user_id
        ).order_by(Roadmap.created_at.desc()).limit(5).all()

        return {
            "roadmaps": [
                {
                    "id": str(r.id),
                    "target_company": r.target_company,
                    "target_role": r.target_role,
                    "weeks_available": r.weeks_available,
                    "roadmap_content": r.roadmap_content,
                    "created_at": r.created_at.isoformat() if r.created_at else None,
                }
                for r in roadmaps
            ]
        }
    finally:
        db.close()

@router.post("/quick-tips")
def get_quick_tips(request: RoadmapRequest):
    """Get 5 quick tips for a specific company and role."""
    try:
        tips = generate_quick_tips(
            target_company=request.target_company,
            target_role=request.target_role,
            missing_skills=request.missing_skills,
        )
        return {"success": True, "tips": tips}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))